name: Python Package 

on : 
   push:
       branches:
           - [ "main" ]
   Pull request:
       types: [opened, synchronised, reopened]
jobs: 
  build: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
       python-version: ["3.9", "3.10", "3.11"]
   steps: 
    - uses: actions/checkout@v3
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with: 
        python-version: ${{ matrix.python-version}} 
    - name: Install dependencies
        run : |
          python -m pip install upgrade pip 
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requiremnets.txt; fi
   - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
   - name: Test with pytest
      run: |
        pytest
        
  buildDockerImageandPush:
     runs-on: ubuntu-latest
     needs: [build] 
     steps: 

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: login to dockerhub
          uses: docker/login-action@v3
          with: 
             username: ${{ secrets.DockerUsername }}
             password: ${{ secrets.DockerPassword }}

        - name: Build and push the image 
          uses: docker/build-push-action@v5
          with: 
            push: true
            tags: shrutipp/snake:latest
